apiVersion: v1
entries:
  utcook:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-04-09T15:49:36.565343771+08:00"
    description: A Helm chart for Kubernetes(new)
    icon: https://utcook-website.oss-cn-shenzhen.aliyuncs.com/logo.png
    keywords:
    - template
    - istio
    - helm
    maintainers:
    - email: hongjun@ut.cn
      name: Hong
    name: utcook
    urls:
    - http://127.0.0.1:8879/charts/utcook-2.1.2.tgz
    version: 2.1.2
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-04-09T15:28:51.122796812+08:00"
    description: A Helm chart for Kubernetes
    home: https://
    keywords:
    - java
    maintainers:
    - email: 29ygq@sina.com
      name: Chinge Yang
    name: utcook
    urls:
    - http://127.0.0.1:8879/utcook-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-04-09T16:09:04.914658684+08:00"
    description: A Helm chart for Kubernetes(new)
    digest: sha256:0c8348175c87f2210040a10d2174d864ae1d8c4a19ef47310764554a7b793ec7
    icon: https://utcook-website.oss-cn-shenzhen.aliyuncs.com/logo.png
    keywords:
    - template
    - istio
    - helm
    maintainers:
    - email: hoenjun@ut.cn
      name: Hong
    name: utcook
    urls:
    - http://127.0.0.1:8879/charts/utcook-2.1.2.tgz
    version: 2.1.2
generated: "2021-04-09T15:28:51.097645792+08:00"
